apiVersion: v1
kind: DeploymentConfig
metadata:
  name: topological-inventory-postgresql
  labels:
    app: topological-inventory
spec:
  strategy:
    type: Recreate
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    name: topological-inventory-postgresql
  template:
    metadata:
      name: topological-inventory-postgresql
      labels:
        name: topological-inventory-postgresql
        app: topological-inventory
    spec:
      volumes:
      - name: topological-inventory-postgresql
        persistentVolumeClaim:
          claimName: topological-inventory-postgresql
      containers:
      - name: topological-inventory-postgresql
        image: docker.io/manageiq/postgresql:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: topological-inventory-postgresql
          mountPath: "/var/lib/pgsql/data"
        env:
        - name: POSTGRESQL_USER
          value: root
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: topological-inventory-database-secrets
              key: database-password
        - name: POSTGRESQL_DATABASE
          value: topological_inventory_production
