apiVersion: v1
kind: DeploymentConfig
metadata:
  name: topological-inventory-kafka
  labels:
    app: topological-inventory
spec:
  replicas: 1
  selector:
    name: topological-inventory-kafka
  template:
    metadata:
      name: topological-inventory-kafka
      labels:
        name: topological-inventory-kafka
        app: topological-inventory
    spec:
      containers:
      - name: topological-inventory-kafka
        image: carbonin/kafka:latest
        command:
        - bin/kafka-server-start.sh
        args:
        - config/server.properties
        - --override
        - advertised.host.name=topological-inventory-kafka
        - --override
        - log.segment.bytes=10485760
        - --override
        - log.retention.bytes=10485760
        volumeMounts:
        - mountPath: /tmp/kafka-logs
          name: topological-inventory-kafka-logs
        ports:
        - containerPort: 9092
      - name: topological-inventory-zookeeper
        image: carbonin/kafka:latest
        command:
        - bin/zookeeper-server-start.sh
        args:
        - config/zookeeper.properties
        volumeMounts:
        - mountPath: /tmp/zookeeper
          name: topological-inventory-zookeeper
        ports:
        - containerPort: 2181
      volumes:
      - name: topological-inventory-kafka-logs
        emptyDir: {}
      - name: topological-inventory-zookeeper
        emptyDir: {}
